 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_C12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C12/TSO_16HR_FIX_C12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C12/TSO_16HR_FIX_C12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D1/TSO_16HR_FIX_D1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D1/TSO_16HR_FIX_D1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D2/TSO_16HR_FIX_D2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D2/TSO_16HR_FIX_D2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D3/TSO_16HR_FIX_D3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D3/TSO_16HR_FIX_D3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D4/TSO_16HR_FIX_D4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D4/TSO_16HR_FIX_D4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D5/TSO_16HR_FIX_D5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D5/TSO_16HR_FIX_D5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D6/TSO_16HR_FIX_D6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D6/TSO_16HR_FIX_D6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D7/TSO_16HR_FIX_D7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D7/TSO_16HR_FIX_D7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D8/TSO_16HR_FIX_D8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D8/TSO_16HR_FIX_D8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D9/TSO_16HR_FIX_D9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D9/TSO_16HR_FIX_D9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D11/TSO_16HR_FIX_D11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D11/TSO_16HR_FIX_D11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_D12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D12/TSO_16HR_FIX_D12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_D12/TSO_16HR_FIX_D12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E1/TSO_30MIN_FIX_E1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E1/TSO_30MIN_FIX_E1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E2/TSO_30MIN_FIX_E2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E2/TSO_30MIN_FIX_E2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E3/TSO_30MIN_FIX_E3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E3/TSO_30MIN_FIX_E3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E4/TSO_30MIN_FIX_E4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E4/TSO_30MIN_FIX_E4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E5/TSO_30MIN_FIX_E5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E5/TSO_30MIN_FIX_E5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E6/TSO_30MIN_FIX_E6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E6/TSO_30MIN_FIX_E6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E7/TSO_30MIN_FIX_E7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E7/TSO_30MIN_FIX_E7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E8/TSO_30MIN_FIX_E8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E8/TSO_30MIN_FIX_E8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E9/TSO_30MIN_FIX_E9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E9/TSO_30MIN_FIX_E9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E11/TSO_30MIN_FIX_E11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E11/TSO_30MIN_FIX_E11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_E12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E12/TSO_30MIN_FIX_E12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_E12/TSO_30MIN_FIX_E12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F1/TSO_30MIN_FIX_F1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F1/TSO_30MIN_FIX_F1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F2/TSO_30MIN_FIX_F2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F2/TSO_30MIN_FIX_F2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F3/TSO_30MIN_FIX_F3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F3/TSO_30MIN_FIX_F3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F4/TSO_30MIN_FIX_F4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F4/TSO_30MIN_FIX_F4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F5/TSO_30MIN_FIX_F5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F5/TSO_30MIN_FIX_F5.ALL 
 

