 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_STATIONARY_PEG_C9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_C9/TSO_STATIONARY_PEG_C9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_C9/TSO_STATIONARY_PEG_C9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_STATIONARY_PEG_C11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_C11/TSO_STATIONARY_PEG_C11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_C11/TSO_STATIONARY_PEG_C11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_STATIONARY_PEG_D3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_D3/TSO_STATIONARY_PEG_D3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_D3/TSO_STATIONARY_PEG_D3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_STATIONARY_PEG_D8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_D8/TSO_STATIONARY_PEG_D8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_D8/TSO_STATIONARY_PEG_D8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_STATIONARY_PEG_D9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_D9/TSO_STATIONARY_PEG_D9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_STATIONARY_PEG_D9/TSO_STATIONARY_PEG_D9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E1/TSO_EXP_NORMAL_E1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E1/TSO_EXP_NORMAL_E1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E2/TSO_EXP_NORMAL_E2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E2/TSO_EXP_NORMAL_E2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E3/TSO_EXP_NORMAL_E3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E3/TSO_EXP_NORMAL_E3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E5/TSO_EXP_NORMAL_E5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E5/TSO_EXP_NORMAL_E5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E7/TSO_EXP_NORMAL_E7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E7/TSO_EXP_NORMAL_E7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E9/TSO_EXP_NORMAL_E9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E9/TSO_EXP_NORMAL_E9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E10/TSO_EXP_NORMAL_E10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E10/TSO_EXP_NORMAL_E10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E11/TSO_EXP_NORMAL_E11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E11/TSO_EXP_NORMAL_E11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_E12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E12/TSO_EXP_NORMAL_E12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_E12/TSO_EXP_NORMAL_E12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_F1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F1/TSO_EXP_NORMAL_F1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F1/TSO_EXP_NORMAL_F1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_F2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F2/TSO_EXP_NORMAL_F2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F2/TSO_EXP_NORMAL_F2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_F3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F3/TSO_EXP_NORMAL_F3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F3/TSO_EXP_NORMAL_F3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_NORMAL_F4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F4/TSO_EXP_NORMAL_F4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_NORMAL_F4/TSO_EXP_NORMAL_F4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_F5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F5/TSO_EXP_100UM_F5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F5/TSO_EXP_100UM_F5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_F6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F6/TSO_EXP_100UM_F6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F6/TSO_EXP_100UM_F6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_F7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F7/TSO_EXP_100UM_F7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F7/TSO_EXP_100UM_F7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_F8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F8/TSO_EXP_100UM_F8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F8/TSO_EXP_100UM_F8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_F9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F9/TSO_EXP_100UM_F9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F9/TSO_EXP_100UM_F9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_F11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F11/TSO_EXP_100UM_F11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_F11/TSO_EXP_100UM_F11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_G1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G1/TSO_EXP_100UM_G1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G1/TSO_EXP_100UM_G1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_G2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G2/TSO_EXP_100UM_G2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G2/TSO_EXP_100UM_G2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_G3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G3/TSO_EXP_100UM_G3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G3/TSO_EXP_100UM_G3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_G6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G6/TSO_EXP_100UM_G6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G6/TSO_EXP_100UM_G6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_G7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G7/TSO_EXP_100UM_G7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G7/TSO_EXP_100UM_G7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_100UM_G8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G8/TSO_EXP_100UM_G8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_100UM_G8/TSO_EXP_100UM_G8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PEG_G10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_G10/TSO_EXP_PEG_G10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_G10/TSO_EXP_PEG_G10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PEG_G12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_G12/TSO_EXP_PEG_G12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_G12/TSO_EXP_PEG_G12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PEG_H1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H1/TSO_EXP_PEG_H1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H1/TSO_EXP_PEG_H1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PEG_H2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H2/TSO_EXP_PEG_H2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H2/TSO_EXP_PEG_H2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PEG_H3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H3/TSO_EXP_PEG_H3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H3/TSO_EXP_PEG_H3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PEG_H4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H4/TSO_EXP_PEG_H4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PEG_H4/TSO_EXP_PEG_H4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PENTA_H10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PENTA_H10/TSO_EXP_PENTA_H10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PENTA_H10/TSO_EXP_PENTA_H10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PENTA_H11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PENTA_H11/TSO_EXP_PENTA_H11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PENTA_H11/TSO_EXP_PENTA_H11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_EXP_PENTA_H12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PENTA_H12/TSO_EXP_PENTA_H12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_EXP_PENTA_H12/TSO_EXP_PENTA_H12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_NORMAL_E12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_NORMAL_E12/NEB_EXP_NORMAL_E12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_NORMAL_E12/NEB_EXP_NORMAL_E12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_100UM_F5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_100UM_F5/NEB_EXP_100UM_F5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_100UM_F5/NEB_EXP_100UM_F5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_100UM_F6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_100UM_F6/NEB_EXP_100UM_F6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_100UM_F6/NEB_EXP_100UM_F6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_100UM_G1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_100UM_G1/NEB_EXP_100UM_G1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_100UM_G1/NEB_EXP_100UM_G1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_PEG_H2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PEG_H2/NEB_EXP_PEG_H2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PEG_H2/NEB_EXP_PEG_H2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_PEG_H3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PEG_H3/NEB_EXP_PEG_H3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PEG_H3/NEB_EXP_PEG_H3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_PEG_H4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PEG_H4/NEB_EXP_PEG_H4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PEG_H4/NEB_EXP_PEG_H4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_PENTA_H11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PENTA_H11/NEB_EXP_PENTA_H11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PENTA_H11/NEB_EXP_PENTA_H11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_EXP_PENTA_H12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PENTA_H12/NEB_EXP_PENTA_H12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_EXP_PENTA_H12/NEB_EXP_PENTA_H12.ALL

