 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F6/TSO_30MIN_FIX_F6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F6/TSO_30MIN_FIX_F6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F7/TSO_30MIN_FIX_F7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F7/TSO_30MIN_FIX_F7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F8/TSO_30MIN_FIX_F8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F8/TSO_30MIN_FIX_F8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F9/TSO_30MIN_FIX_F9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F9/TSO_30MIN_FIX_F9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F10/TSO_30MIN_FIX_F10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F10/TSO_30MIN_FIX_F10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_F11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F11/TSO_30MIN_FIX_F11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_F11/TSO_30MIN_FIX_F11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G1/TSO_30MIN_FIX_G1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G1/TSO_30MIN_FIX_G1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G2/TSO_30MIN_FIX_G2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G2/TSO_30MIN_FIX_G2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D7/NEB_16HR_FIX_D7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D7/NEB_16HR_FIX_D7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D8/NEB_16HR_FIX_D8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D8/NEB_16HR_FIX_D8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D9/NEB_16HR_FIX_D9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D9/NEB_16HR_FIX_D9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D10/NEB_16HR_FIX_D10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D10/NEB_16HR_FIX_D10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D11/NEB_16HR_FIX_D11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D11/NEB_16HR_FIX_D11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D12/NEB_16HR_FIX_D12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D12/NEB_16HR_FIX_D12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E1/NEB_30MIN_FIX_E1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E1/NEB_30MIN_FIX_E1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E2/NEB_30MIN_FIX_E2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E2/NEB_30MIN_FIX_E2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E3/NEB_30MIN_FIX_E3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E3/NEB_30MIN_FIX_E3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E4/NEB_30MIN_FIX_E4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E4/NEB_30MIN_FIX_E4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E5/NEB_30MIN_FIX_E5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E5/NEB_30MIN_FIX_E5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E7/NEB_30MIN_FIX_E7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E7/NEB_30MIN_FIX_E7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E8/NEB_30MIN_FIX_E8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E8/NEB_30MIN_FIX_E8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E9/NEB_30MIN_FIX_E9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E9/NEB_30MIN_FIX_E9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E11/NEB_30MIN_FIX_E11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E11/NEB_30MIN_FIX_E11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_E12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E12/NEB_30MIN_FIX_E12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_E12/NEB_30MIN_FIX_E12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F1/NEB_30MIN_FIX_F1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F1/NEB_30MIN_FIX_F1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F2/NEB_30MIN_FIX_F2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F2/NEB_30MIN_FIX_F2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F3/NEB_30MIN_FIX_F3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F3/NEB_30MIN_FIX_F3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F4/NEB_30MIN_FIX_F4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F4/NEB_30MIN_FIX_F4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F5/NEB_30MIN_FIX_F5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F5/NEB_30MIN_FIX_F5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F6/NEB_30MIN_FIX_F6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F6/NEB_30MIN_FIX_F6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F7/NEB_30MIN_FIX_F7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F7/NEB_30MIN_FIX_F7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F8/NEB_30MIN_FIX_F8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F8/NEB_30MIN_FIX_F8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F9/NEB_30MIN_FIX_F9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F9/NEB_30MIN_FIX_F9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F10/NEB_30MIN_FIX_F10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F10/NEB_30MIN_FIX_F10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_F11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F11/NEB_30MIN_FIX_F11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_F11/NEB_30MIN_FIX_F11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G1/NEB_30MIN_FIX_G1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G1/NEB_30MIN_FIX_G1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G2/NEB_30MIN_FIX_G2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G2/NEB_30MIN_FIX_G2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G3/NEB_30MIN_FIX_G3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G3/NEB_30MIN_FIX_G3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G4/NEB_30MIN_FIX_G4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G4/NEB_30MIN_FIX_G4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G5/NEB_30MIN_FIX_G5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G5/NEB_30MIN_FIX_G5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G6/NEB_30MIN_FIX_G6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G6/NEB_30MIN_FIX_G6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G7/NEB_30MIN_FIX_G7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G7/NEB_30MIN_FIX_G7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G8/NEB_30MIN_FIX_G8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G8/NEB_30MIN_FIX_G8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G9/NEB_30MIN_FIX_G9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G9/NEB_30MIN_FIX_G9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G10/NEB_30MIN_FIX_G10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G10/NEB_30MIN_FIX_G10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_G12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G12/NEB_30MIN_FIX_G12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_G12/NEB_30MIN_FIX_G12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_H1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H1/NEB_30MIN_FIX_H1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H1/NEB_30MIN_FIX_H1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_H2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H2/NEB_30MIN_FIX_H2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H2/NEB_30MIN_FIX_H2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_H3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H3/NEB_30MIN_FIX_H3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H3/NEB_30MIN_FIX_H3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_H4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H4/NEB_30MIN_FIX_H4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H4/NEB_30MIN_FIX_H4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_H5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H5/NEB_30MIN_FIX_H5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H5/NEB_30MIN_FIX_H5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_H6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H6/NEB_30MIN_FIX_H6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H6/NEB_30MIN_FIX_H6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_H7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H7/NEB_30MIN_FIX_H7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_H7/NEB_30MIN_FIX_H7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_PENTA_H8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_PENTA_H8/NEB_30MIN_FIX_PENTA_H8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_PENTA_H8/NEB_30MIN_FIX_PENTA_H8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_PENTA_H11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_PENTA_H11/NEB_30MIN_FIX_PENTA_H11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_PENTA_H11/NEB_30MIN_FIX_PENTA_H11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_30MIN_FIX_PENTA_H12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_PENTA_H12/NEB_30MIN_FIX_PENTA_H12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_30MIN_FIX_PENTA_H12/NEB_30MIN_FIX_PENTA_H12.ALL 

