 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G3/TSO_30MIN_FIX_G3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G3/TSO_30MIN_FIX_G3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G5/TSO_30MIN_FIX_G5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G5/TSO_30MIN_FIX_G5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G6/TSO_30MIN_FIX_G6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G6/TSO_30MIN_FIX_G6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G7/TSO_30MIN_FIX_G7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G7/TSO_30MIN_FIX_G7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G8 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G8/TSO_30MIN_FIX_G8.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G8/TSO_30MIN_FIX_G8.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G9/TSO_30MIN_FIX_G9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G9/TSO_30MIN_FIX_G9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G10/TSO_30MIN_FIX_G10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G10/TSO_30MIN_FIX_G10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_G12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G12/TSO_30MIN_FIX_G12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_G12/TSO_30MIN_FIX_G12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_H1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H1/TSO_30MIN_FIX_H1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H1/TSO_30MIN_FIX_H1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_H2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H2/TSO_30MIN_FIX_H2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H2/TSO_30MIN_FIX_H2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_H3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H3/TSO_30MIN_FIX_H3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H3/TSO_30MIN_FIX_H3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_H4 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H4/TSO_30MIN_FIX_H4.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H4/TSO_30MIN_FIX_H4.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_H5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H5/TSO_30MIN_FIX_H5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H5/TSO_30MIN_FIX_H5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_H6 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H6/TSO_30MIN_FIX_H6.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H6/TSO_30MIN_FIX_H6.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_H7 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H7/TSO_30MIN_FIX_H7.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_H7/TSO_30MIN_FIX_H7.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_PENTA_H9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H9/TSO_30MIN_FIX_PENTA_H9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H9/TSO_30MIN_FIX_PENTA_H9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_PENTA_H10 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H10/TSO_30MIN_FIX_PENTA_H10.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H10/TSO_30MIN_FIX_PENTA_H10.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_PENTA_H11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H11/TSO_30MIN_FIX_PENTA_H11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H11/TSO_30MIN_FIX_PENTA_H11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_30MIN_FIX_PENTA_H12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H12/TSO_30MIN_FIX_PENTA_H12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_30MIN_FIX_PENTA_H12/TSO_30MIN_FIX_PENTA_H12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_C9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_C9/NEB_16HR_FIX_C9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_C9/NEB_16HR_FIX_C9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_C11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_C11/NEB_16HR_FIX_C11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_C11/NEB_16HR_FIX_C11.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_C12 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_C12/NEB_16HR_FIX_C12.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_C12/NEB_16HR_FIX_C12.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D1 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D1/NEB_16HR_FIX_D1.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D1/NEB_16HR_FIX_D1.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D2 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D2/NEB_16HR_FIX_D2.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D2/NEB_16HR_FIX_D2.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D3 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D3/NEB_16HR_FIX_D3.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D3/NEB_16HR_FIX_D3.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name NEB_16HR_FIX_D5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D5/NEB_16HR_FIX_D5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/NEB_16HR_FIX_D5/NEB_16HR_FIX_D5.ALL 
/Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_C5 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C5/TSO_16HR_FIX_C5.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C5/TSO_16HR_FIX_C5.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_C9 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C9/TSO_16HR_FIX_C9.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C9/TSO_16HR_FIX_C9.ALL 
 
 /Genomics/grid/users/bw21/miniconda3/envs/cutadaptenv/bin/python3.7 -u -m scifi.scripts.summarizer --r1-annot /Genomics/grid/users/bw21/gitrepos/scBactoSeq/data/Barcodes/bw_scifi2_plate_anno.csv --r1-attributes plate_well,treatment --cell-barcodes r1 r2 --only-summary --no-save-intermediate --min-umi-output 5 --expected-cell-number 600000 --no-output-header --save-gene-expression --correct-r1-barcodes --species-mixture --sample-name TSO_16HR_FIX_C11 /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C11/TSO_16HR_FIX_C11.ALL.STAR.Aligned.out.bam.featureCounts.bam /Genomics/grid/users/bw21/Data/bw_scifi2_2_map_out/bw_scifi2_2/TSO_16HR_FIX_C11/TSO_16HR_FIX_C11.ALL 

